### ISSUE TITLE
Travis info

### ISSUE THREAD

**Issue by Ismaestro** [kendaleiv/angular-testing#24]
Hello!

You should update readme file to explain travis configuration. Specially this part:

```
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
```

This help me very much to run e2e tests in travis ci.

:)

**Comment by kendaleiv** [comment]
Does this help at all? https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by Ismaestro** [comment]
Yes, it does. Thanks
